import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,mkdtempSync} from 'node:fs';
import {handleHub} from '../work/hub-service-test.mjs';
import {respond} from '../work/provider-test.mjs';
const dir=mkdtempSync('work/test-');const filename=dir+'/hub.sqlite';let sql=new DatabaseSync(filename);sql.exec('PRAGMA foreign_keys=ON');
for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
function statement(query,params=[]){return{bind(...p){return statement(query,p);},async first(){return sql.prepare(query).get(...params)||null;},async all(){return{results:sql.prepare(query).all(...params)};},async run(){return sql.prepare(query).run(...params);}};}
const db={prepare:statement,async batch(stmts){sql.exec('BEGIN');try{const out=[];for(const s of stmts)out.push(await s.run());sql.exec('COMMIT');return out;}catch(e){sql.exec('ROLLBACK');throw e;}}};
let deferred=[];let calls=0;
const ctx={db,user:'gabriel-test',config:null,dailyLimit:2,defer:p=>deferred.push(p),provider:async()=>{calls++;return{text:'Resposta de teste',usage:{input_tokens:10,output_tokens:5}};}};
async function request(path,method='GET',body,override={}){const r=await handleHub(new Request('https://hub.test/api/hub/'+path,{method,headers:body?{'Content-Type':'application/json',Origin:'https://hub.test'}:undefined,body:body?JSON.stringify(body):undefined}),{...ctx,...override});return{status:r.status,data:await r.json()};}
async function drain(){await Promise.all(deferred);deferred=[];}
const id=crypto.randomUUID();
assert.equal((await request('conversations','GET',undefined,{user:null})).status,401);
assert.equal((await request('conversations','POST',{id,agentId:'faculdade'})).status,201);
assert.equal((await request('conversations/'+id,'GET',undefined,{user:'other'})).status,404);
assert.equal((await request('conversations','GET',undefined,{user:'other'})).data.conversations.length,0);
console.log('PASS: autenticação e isolamento por proprietário');
const first={content:'Mensagem persistente',key:crypto.randomUUID()};
let sent=await request('conversations/'+id+'/messages','POST',first);
assert.equal(sent.status,202);assert.equal(sent.data.run.status,'failed');assert.equal(sent.data.messages.length,1);assert.equal(calls,0);
assert.equal((await request('conversations/'+id+'/messages','POST',first)).data.messages.length,1);
assert.equal((await request('conversations/'+id+'/messages','POST',{...first,content:'alterada'})).status,409);
sql.close();sql=new DatabaseSync(filename);sql.exec('PRAGMA foreign_keys=ON');
assert.equal((await request('conversations/'+id)).data.messages[0].content,'Mensagem persistente');
console.log('PASS: persistência após reabrir banco, idempotência e ausência de respostas simuladas');
ctx.config={kind:'openai',key:'unit-test-only',model:'unit-test-model'};
sent=await request('conversations/'+id+'/retry','POST',{key:crypto.randomUUID()});assert.equal(sent.status,202);await drain();
let snap=await request('conversations/'+id);assert.equal(snap.data.run.status,'completed');assert.equal(snap.data.messages.length,2);assert.equal(calls,1);
await request('conversations/'+id+'/messages','POST',{key:crypto.randomUUID(),content:'Outra'});await drain();
assert.equal(calls,2);
const before=(await request('conversations/'+id)).data.messages.length;
assert.equal((await request('conversations/'+id+'/messages','POST',{key:crypto.randomUUID(),content:'Acima do limite'})).status,409);
assert.equal((await request('conversations/'+id)).data.messages.length,before);
console.log('PASS: execução, nova tentativa e limite diário sem mensagem órfã');
const cancelledId=crypto.randomUUID();await request('conversations','POST',{id:cancelledId,agentId:'ipe'});ctx.dailyLimit=10;
let release;let started;const startedPromise=new Promise(r=>started=r);
const delayed=async()=>{started();return new Promise(r=>release=r);};
await request('conversations/'+cancelledId+'/messages','POST',{key:crypto.randomUUID(),content:'Cancelar teste'},{provider:delayed});await startedPromise;
assert.equal((await request('conversations/'+id+'/messages','POST',{key:crypto.randomUUID(),content:'Concorrente'})).status,409);
await request('conversations/'+cancelledId+'/cancel','POST',{});release({text:'Não persistir esta resposta'});await drain();
snap=await request('conversations/'+cancelledId);assert.equal(snap.data.run.status,'cancelled');assert.equal(snap.data.messages.length,1);
console.log('PASS: execução concorrente recusada e cancelamento sem resposta tardia');
const exports=await request('export');assert.equal(exports.data.conversations.length,2);assert.equal((await request('export','GET',undefined,{user:'other'})).data.messages.length,0);
const csrf=await handleHub(new Request('https://hub.test/api/hub/conversations',{method:'POST',headers:{Origin:'https://evil.test','Content-Type':'application/json'},body:'{}'}),ctx);assert.equal(csrf.status,403);
console.log('PASS: exportação privada e bloqueio de origem externa');
let wire;const response=await respond(ctx.config,'instruções',[{role:'user',content:'Olá'}],new AbortController().signal,async(url,options)=>{wire={url,...options};return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'OK'}]}]});});
assert.equal(response.text,'OK');assert.equal(wire.url,'https://api.openai.com/v1/responses');assert.equal(JSON.parse(wire.body).store,false);assert.equal(JSON.parse(wire.body).max_output_tokens,3000);
await assert.rejects(respond(ctx.config,'',[],new AbortController().signal,async()=>Response.json({status:'incomplete',output:[]})),/incompleta/);
await assert.rejects(respond(ctx.config,'',[],new AbortController().signal,async()=>new Response('{}',{status:401})),/chave/);
await assert.rejects(respond(ctx.config,'',[],new AbortController().signal,async()=>Response.json({error:{code:'credit_balance_exhausted',type:'insufficient_quota',message:'private upstream detail'}},{status:429})),/saldo da API acabou/);
await assert.rejects(respond(ctx.config,'',[],new AbortController().signal,async()=>Response.json({error:{code:'insufficient_quota'}},{status:429})),/sem cota disponível/);
await assert.rejects(respond(ctx.config,'',[],new AbortController().signal,async()=>Response.json({error:{code:'rate_limit_exceeded'}},{status:429})),/Muitas solicitações/);
await assert.rejects(respond(ctx.config,'',[],new AbortController().signal,async()=>Response.json({error:{code:'model_not_found'}},{status:404})),/acesso ao modelo/);
await assert.rejects(respond(ctx.config,'',[],new AbortController().signal,async()=>new Response('private upstream detail',{status:502})),/não respondeu corretamente/);
let ollamaWire;const local=await respond({kind:'ollama',model:'local-test',baseUrl:'http://127.0.0.1:11434'},'instruções',[{role:'user',content:'Olá'}],new AbortController().signal,async(url,options)=>{ollamaWire={url,...options};return Response.json({message:{content:'Resposta local'},prompt_eval_count:8,eval_count:3});});
assert.equal(local.text,'Resposta local');assert.equal(ollamaWire.url,'http://127.0.0.1:11434/api/chat');assert.equal(JSON.parse(ollamaWire.body).stream,false);assert.equal(JSON.parse(ollamaWire.body).messages[0].role,'system');
let n8nWire;const routed=await respond({kind:'n8n',model:'n8n-router',webhookUrl:'https://n8n.example/webhook/gabriel-ai-hub',webhookSecret:'test-secret'},'',[],new AbortController().signal,async(url,options)=>{n8nWire={url,...options};return Response.json({conversationId:'conv-1',agentId:'faculdade',reply:'Resposta do n8n',memoryCandidates:[],citations:[],followUp:''});},{userId:'gabriel-test',agentId:'faculdade',conversationId:'conv-1',requestId:'req-1',message:'Olá',userMemory:{},agentMemory:{},attachments:[],locale:'pt-BR',timezone:'America/Sao_Paulo'});
assert.equal(routed.text,'Resposta do n8n');assert.equal(n8nWire.url,'https://n8n.example/webhook/gabriel-ai-hub');assert.equal(n8nWire.headers['X-Gabriel-Hub-Secret'],'test-secret');const n8nBody=JSON.parse(n8nWire.body);assert.equal(n8nBody.userId,'gabriel-test');assert.equal(n8nBody.conversationId,'conv-1');assert.equal(n8nBody.requestId,'req-1');assert.equal(n8nBody.agentId,'faculdade');
const clarified=await respond({kind:'n8n',model:'n8n-router',webhookUrl:'https://n8n.example/webhook/gabriel-ai-hub'},'',[],new AbortController().signal,async()=>Response.json({conversationId:'conv-2',agentId:'clarify',reply:"A rota 'clarify' não é uma rota válida deste roteador.",memoryCandidates:[],citations:[],followUp:''}),{userId:'gabriel-test',agentId:'faculdade',conversationId:'conv-2',requestId:'req-2',message:'O que você faz?',userMemory:{},agentMemory:{},attachments:[],locale:'pt-BR',timezone:'America/Sao_Paulo'});
assert.equal(clarified.text,'Posso ajudar com Faculdade, Concursos, IPE Trading ou Carreira & Tecnologia. Qual dessas áreas você quer usar?');
console.log('PASS: contrato do provedor e falhas; nenhuma chamada real de IA');sql.close();

